### ISSUE TITLE
Deploying multiple Lambdas at once

### ISSUE THREAD

**Issue by eneko** [swift-server/swift-aws-lambda-runtime#117]
I've been wondering what would be the best approach for deploying multiple lambdas at once, so I'm hoping to use this issue thread as a place to discuss the best strategy for this. If there is a better place, like forums.swift.org, let me know.

I don't have much experience with lambda, however, I can imagine the following scenarios:
- Swift package with single function
- Swift package with multiple, independent functions
- Swift package with multiple functions sharing resources (eg. same DynamoDB table, same AWS Gateway API, ...)

I'd like to assume for each of those scenarios, being able to deploy lambdas individually (this is, update a single lambda and deploy it) should remain an option.

Focusing on SAM for now, there are two approaches: 
- One SAM template per function
- One SAM template per application, with multiple functions

What would be the recommended layout for projects with many functions? What are the pros and cons of one template for multiple lambdas vs one template per function?

**Comment by tomerd** [comment]
@eneko your observation that the current deployment examples focus on single function executable is correct

users of this library may of course choose to build "larger" packages that include many executables in them. we did not emphasize this option in the documentation and example as it leads to lager packages that have slower start time (AWS needs to download a larger zipfile, etc)

**Comment by eneko** [comment]
Thanks for the feedback, @tomerd 

I read #57, and found it interesting. For sure, it would be nice to support the "handler" name entered in Lambda configuration page, so a single binary could be used for multiple functions.

In the cases stated above in this issue, I was thinking on the scenario where a Package contains multiple binaries (multiple executable products), one executable per Lambda function. This is, following how [Lambda Functions Examples](https://github.com/swift-server/swift-aws-lambda-runtime/tree/master/Examples/LambdaFunctions) are set up.

The question I had is on what would be the best approach for budding, packaging and deploying multiple binaries at the same time, using SAM for example. Hope that makes sense.

**Comment by eneko** [comment]
Might be a good idea to document terminology. For example, here we are talking about two different packages:

- Swift Packages (the “project” used in Xcode)
- Packages downloaded by Lambda during a cold start.

Using a single SAM template to deploy multiple lambdas in a Swift Package shouldn’t make each packaged lambda larger in size. 

Hope I’m making sense.

**Comment by fabianfett** [comment]
Hi @eneko,

> I read #57, and found it interesting. For sure, it would be nice to support the "handler" name entered in Lambda configuration page, so a single binary could be used for multiple functions.

As stated in #57 you can use the `_HANDLER` env variable without any problem and you're free to do so.

> The question I had is on what would be the best approach for budding, packaging and deploying multiple binaries at the same time, using SAM for example. Hope that makes sense.

You can just throw your sam templates into each other. If you want to you could deploy all example Lambas with just one sam template if you copy and pasted all the sam templates into one file.

Just make sure all your resources have different names.
Does that solve your issue?

**Comment by eneko** [comment]
@fabianfett thanks for the feedback. This is not really an issue, just trying to find out what the best practices are, so we could update scripts if needed, and/or document different approaches.

For example, on a demo project I'm working on, I have two lambda functions that use the same DynamoDB table. Having both functions in the same SAM template, together with the DynamoDB table definition, allows for using resource references instead of manually specifying the ARN:

```
oneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build/lambda/FunctionA/lambda.zip
      [...]
      # Grants this function permission to perform actions on the table
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              [...]
            Resource: !GetAtt backendTable.Arn    <--- this

anotherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build/lambda/FunctionB/lambda.zip
      [...]
      # Grants this function permission to perform actions on the table
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              [...]
            Resource: !GetAtt backendTable.Arn    <--- this

backendTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      [...]
```

However, in order to deploy this SAM template, both `FunctionA` and `FunctionB` have to be built and packaged.

This can easily be done with a deploy script like this:
```
echo "-------------------------------------------------------------------------"
echo "preparing docker build image"
echo "-------------------------------------------------------------------------"
docker build . -q -t builder

$DIR/build-and-package.sh FunctionA
$DIR/build-and-package.sh FunctionB

echo "-------------------------------------------------------------------------"
echo "deploying using SAM"
echo "-------------------------------------------------------------------------"

sam deploy --template "template.yml" $@
```

I'm not sure if this follows best practices, or if there is a better approach. 

Thanks!

**Comment by fabianfett** [comment]
> I'm not sure if this follows best practices, or if there is a better approach.

Well, I don't know if there is a better approach either, but that's pretty close to what I'm doing ;)

**Comment by tomerd** [comment]
@eneko would you like to PR some docs around this so we can close it out?

**Comment by pokryfka** [comment]
@eneko 

> For example, on a demo project I'm working on, I have two lambda functions that use the same DynamoDB table. Having both functions in the same SAM template, together with the DynamoDB table definition, allows for using resource references instead of manually specifying the ARN:

one approach to address that is to have many Lambda function in the same SAM template (which also defines other AWS resources) but to package and deploy each function separately

**Comment by pokryfka** [comment]
@eneko 

As far as I know SAM CLI packages each function separately.
This used to work for supported runtimes only.
With recent SAM CLI release (1.1.0) you can configure makefile build method in SAM template and, as long as you define build targets (which could be just one with wildcard) `sam build` will package all each function for you.

```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: my.bootstrap.file
      Runtime: provided.al2
    Metadata:
      BuildMethod: makefile
```

References: 
- https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-al2/
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html
